import sys

def main(argv):
	argc = len(sys.argv)
	if argv[1] == "maketable":
		of = open("out.txt",'w')
		of.write("; Generated by wsfreq.py\nFreqTable:")
		for	i in range(0,132):
			if (i - 36) % 12 == 0:
				of.write("\n    dw      ")
			x = float(argv[0]) * pow(2, (i - 69) / 12)
			y = 2048 - (3072000 / 32 / x)
			of.write('0x%x,' % int(y))
		of.close()
	else:
		x = float(argv[0]) * pow(2, (float(argv[1]) - 69) / 12)
		y = 2048 - (3072000 / 32 / x)
		print("a =",argv[0],"  midi note:",argv[1],"  freq:",x,"  WS:",'0x%x'%int(y))
	
if __name__ == "__main__":
	main(sys.argv[1:])